version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    container_name: mosquitto
    env_file:
      - '${INSTALL_DIRECTORY}/mosquitto/config/env.mosquitto'
    volumes:
      - ${INSTALL_DIRECTORY}/mosquitto/data:/mosquitto/data
      - ${INSTALL_DIRECTORY}/mosquitto/log:/mosquitto/log
      - ${INSTALL_DIRECTORY}/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  influxdb:
    image: influxdb:alpine
    restart: always
    container_name: influxdb
    env_file:
      - '${INSTALL_DIRECTORY}/influxdb/config/env.influxdb'
    volumes:
      - ${INSTALL_DIRECTORY}/influxdb/data:/var/lib/influxdb

  nodered:
    image: nodered/node-red:latest
    restart: always
    container_name: nodered
    user: '0'
    links:
      - influxdb
      - mosquitto
    env_file:
      - '${INSTALL_DIRECTORY}/nodered/data/env.nodered'
    volumes:
      - ${INSTALL_DIRECTORY}/nodered/data:/data

  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: grafana
    env_file:
      - '${INSTALL_DIRECTORY}/grafana/config/env.grafana'
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p ${INSTALL_DIRECTORY}/docker/grafana/data; chown 472:472 ${INSTALL_DIRECTORY}/docker/grafana/data
      - ${INSTALL_DIRECTORY}/grafana/data:/var/lib/grafana

  haproxy-certbot:
    image: bisand/haproxy-certbot
    container_name: haproxy-certbot
    restart: always
    env_file:
      - '${INSTALL_DIRECTORY}/haproxy/config/env.haproxy'
    ports:
      - ${PORT_HAPROXY_HTTP}:${PORT_HAPROXY_HTTP}
      - ${PORT_HAPROXY_HTTPS}:${PORT_HAPROXY_HTTPS}
      - ${PORT_HAPROXY_MQTT}:${PORT_HAPROXY_MQTT}
      - ${PORT_HAPROXY_MQTTS}:${PORT_HAPROXY_MQTTS}
    links:
      - grafana
    cap_add:
      - NET_ADMIN
    volumes:
      # Data persistency
      # sudo mkdir -p ${INSTALL_DIRECTORY}/data/config
      # sudo mkdir -p ${INSTALL_DIRECTORY}/data/letsencrypt
      # sudo mkdir -p ${INSTALL_DIRECTORY}/data/certs
      - ${INSTALL_DIRECTORY}/haproxy/config:/config
      - ${INSTALL_DIRECTORY}/haproxy/data:/etc/letsencrypt
      - ${INSTALL_DIRECTORY}/haproxy/certs:/usr/local/etc/haproxy/certs.d
