version: '3.4'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /mnt/docker/iotserver/mosquitto/data:/mosquitto/data
      - /mnt/docker/iotserver/mosquitto/log:/mosquitto/log
      - /mnt/docker/iotserver/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - app-net
      - backend-network

  influxdb:
    image: influxdb:1.8-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /mnt/docker/iotserver/influxdb/data:/var/lib/influxdb
    networks:
      - app-net
      - backend-network

  nodered:
    image: nodered/node-red:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    user: '0'
    links:
      - influxdb
      - mosquitto
    ports:
      - 1880:1880
    volumes:
      - /mnt/docker/iotserver/nodered/data:/data
    networks:
      - app-net
      - backend-network

  grafana:
    image: grafana/grafana:7.0.6 # Newer versions tend to not work on legacy IOS devices.
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_SECURITY_ALLOW_EMBEDDING: true
    links:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      # Data persistency
      - /mnt/docker/iotserver/grafana/data:/var/lib/grafana
    networks:
      - app-net
      - backend-network

networks:
  app-net:
    driver: overlay
  backend-network:
    external: true
