version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    container_name: mosquitto
    env_file:
      - '~/data/config/env.mosquitto'
    volumes:
      - /srv/docker/mosquitto/data:/mosquitto/data
      - /srv/docker/mosquitto/log:/mosquitto/log
      - ~/data/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  influxdb:
    image: influxdb:latest
    restart: always
    container_name: influxdb
    env_file:
      - '~/data/config/env.influxdb'
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb

  nodered:
    image: nodered/node-red-docker:slim
    restart: always
    container_name: nodered
    user: '0'
    links:
      - influxdb
      - mosquitto
    env_file:
      - '~/data/config/env.nodered'
    volumes:
      - /srv/docker/nodered/data:/data
      - ~/data/config/nodered_settings.js:/data/settings.js:ro

  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: grafana
    env_file:
      - '~/data/config/env.grafana'
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - /srv/docker/grafana/data:/var/lib/grafana

  haproxy-certbot:
    image: nmarus/haproxy-certbot
    container_name: haproxy-certbot
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1883:1883
      - 8883:8883
    links:
      - grafana
    cap_add:
      - NET_ADMIN
    volumes:
      # Data persistency
      # sudo mkdir -p ~/data/config
      # sudo mkdir -p ~/data/letsencrypt
      # sudo mkdir -p ~/data/certs
      - ~/data/config:/config
      - ~/data/letsencrypt:/etc/letsencrypt
      - ~/data/certs:/usr/local/etc/haproxy/certs.d
