version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    container_name: mosquitto
    env_file:
      - '${INSTALL_FOLDER}/mosquitto/config/env.mosquitto'
    volumes:
      - ${INSTALL_FOLDER}/mosquitto/data:/mosquitto/data
      - ${INSTALL_FOLDER}/mosquitto/log:/mosquitto/log
      - ${INSTALL_FOLDER}/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  influxdb:
    image: influxdb:alpine
    restart: always
    container_name: influxdb
    env_file:
      - '${INSTALL_FOLDER}/influxdb/config/env.influxdb'
    volumes:
      - ${INSTALL_FOLDER}/influxdb/data:/var/lib/influxdb

  nodered:
    image: nodered/node-red:latest
    restart: always
    container_name: nodered
    user: '0'
    links:
      - influxdb
      - mosquitto
    env_file:
      - '${INSTALL_FOLDER}/nodered/data/env.nodered'
    volumes:
      - ${INSTALL_FOLDER}/nodered/data:/data

  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: grafana
    env_file:
      - '${INSTALL_FOLDER}/grafana/config/env.grafana'
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p ${INSTALL_FOLDER}/docker/grafana/data; chown 472:472 ${INSTALL_FOLDER}/docker/grafana/data
      - ${INSTALL_FOLDER}/grafana/data:/var/lib/grafana

  allegutta-portfolio:
    image: bisand/allegutta-portfolio:latest
    restart: always
    container_name: allegutta-portfolio
    env_file:
      - '${INSTALL_FOLDER}/allegutta/config/env.allegutta'
    volumes:
      # Data persistency
      - ${INSTALL_FOLDER}/allegutta/data:/usr/src/app/data
      - ${INSTALL_FOLDER}/allegutta/log:/usr/src/app/log
      - ${INSTALL_FOLDER}/allegutta/config:/usr/src/app/config

  haproxy-certbot:
    image: bisand/haproxy-certbot
    container_name: haproxy-certbot
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1883:1883
      - 8883:8883
    links:
      - grafana
    cap_add:
      - NET_ADMIN
    volumes:
      # Data persistency
      # sudo mkdir -p ${INSTALL_FOLDER}/data/config
      # sudo mkdir -p ${INSTALL_FOLDER}/data/letsencrypt
      # sudo mkdir -p ${INSTALL_FOLDER}/data/certs
      - ${INSTALL_FOLDER}/haproxy/config:/config
      - ${INSTALL_FOLDER}/haproxy/data:/etc/letsencrypt
      - ${INSTALL_FOLDER}/haproxy/certs:/usr/local/etc/haproxy/certs.d
