version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    container_name: mosquitto
    env_file:
      - './_iotserver/data/config/env.mosquitto'
    volumes:
      - ./_iotserver/docker/mosquitto/data:/mosquitto/data
      - ./_iotserver/docker/mosquitto/log:/mosquitto/log
      - ./_iotserver/data/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  influxdb:
    image: influxdb:latest
    restart: always
    container_name: influxdb
    env_file:
      - './_iotserver/data/config/env.influxdb'
    volumes:
      - ./_iotserver/docker/influxdb/data:/var/lib/influxdb

  nodered:
    image: nodered/node-red-docker:slim
    restart: always
    container_name: nodered
    user: '0'
    links:
      - influxdb
      - mosquitto
    env_file:
      - './_iotserver/data/config/env.nodered'
    volumes:
      - ./_iotserver/docker/nodered/data:/data
      - ./_iotserver/data/config/nodered_settings.js:/data/settings.js:ro

  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: grafana
    env_file:
      - './_iotserver/data/config/env.grafana'
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p ./_iotserver/docker/grafana/data; chown 472:472 ./_iotserver/docker/grafana/data
      - ./_iotserver/docker/grafana/data:/var/lib/grafana

  haproxy-certbot:
    image: bisand/haproxy-certbot
    container_name: haproxy-certbot
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1883:1883
      - 8883:8883
    links:
      - grafana
    cap_add:
      - NET_ADMIN
    volumes:
      # Data persistency
      # sudo mkdir -p ./_iotserver/data/config
      # sudo mkdir -p ./_iotserver/data/letsencrypt
      # sudo mkdir -p ./_iotserver/data/certs
      - ./_iotserver/data/config:/config
      - ./_iotserver/data/letsencrypt:/etc/letsencrypt
      - ./_iotserver/data/certs:/usr/local/etc/haproxy/certs.d
